---
# DEBIAN

- name: OpenDKIM is installed via aptitude
  apt: 
    name: "{{item}}"
    state: installed 
  with_items:
    - opendkim
    - opendkim-tools
    - libopendbx1-mysql
  notify:
    - restart opendkim linux

- stat:
    path: /etc/systemd/system/opendkim.service
  register: _opendkim_systemd_service_file

- name: Debian's default opendkim service is disabled
  service:
    name: opendkim
    state: stopped
    enabled: false
  when: not _opendkim_systemd_service_file.stat.exists

- name: OpenDKIM systemd service is available
  template:
    src: "systemd/system/opendkim.service.j2"
    dest: "/etc/systemd/system/opendkim.service"
    owner: root
    group: root
    mode: 0766

- name: OpenDKIM systemd service is enabled
  service:
    name: opendkim
    enabled: true
    state: started
