---

- fail: msg="opendkim_mysql is required"
  when: opendkim_mysql is not defined

- set_fact: _opendkim_config="{{ opendkim_default_config | combine(opendkim_config, recursive=True) }}"
  no_log: true

- include: prepare.yml
- include: install.yml
- include: configure.yml
