---

- name: DKIM daemon and milter goups exist
  group:
    name: "{{ item }}"
    state: present
    system: yes
  with_items: "{{ [ _opendkim_config.daemon_group, _opendkim_config.milter.group ] }}"

- name: DKIM daemon user exists and is assigned to additional groups
  user:
    name: "{{ _opendkim_config.daemon_user }}"
    group: "{{ _opendkim_config.daemon_group }}"
    groups: "{{ _opendkim_config.milter.group }}"
    append: yes
    system: yes
    state: present
  notify:
    - restart opendkim linux
    - restart opendkim freebsd

- name: milter directory exists and is owned by milter group
  file:
    path: "{{ _opendkim_config.milter.socket_path | dirname }}"
    state: directory
    group: "{{ _opendkim_config.milter.group }}"
    mode: "g=rwx"
