---

- name: restart opendkim linux
  service: name=opendkim state=restarted
  when: ansible_distribution == "Debian"

- name: restart opendkim freebsd
  service: name=milter-opendkim state=restarted
  when: ansible_distribution == "FreeBSD"
